### PR TITLE
v5.4.36

### PR DESCRIPTION
**Pull request by Zhastreaus**
Support for laravel 5.4

### CODE REVIEW

**Comment by nunomaduro** [comment]
@Zhastreaus Thanks for PR. I am curious: Why you need this?

**Comment by Zhastreaus** [comment]
I am currently importing illuminate components on a project running in PHP 5.6 and Laravel 5.4 is the last latest version of Laravel that supports PHP 5.6

**Comment by nunomaduro** [comment]
@Zhastreaus I understand! Do you mind that I take a look on this next weekend? Any urgency?

**Comment by Zhastreaus** [comment]
I'm currently using my fork as it needs to be used ASAP so it's alright. You can take your time :)

**Comment by nunomaduro** [comment]
Sorry buddy, but there is no plans of supporting this version on this package. Thanks anyway!

**Pull request closed without merging**
