### PR TITLE
chore: update the Foundation to v8.19.0

### PR DESCRIPTION
**Pull request by owenvoke**
I noticed that Laravel core now includes a [`schedule:list` command](https://github.com/laravel/framework/pull/35574). Currently in the framework, we have a [`schedule-list` component](https://github.com/laravel-zero/framework/tree/56ce9746f88bfe79b937930bf375e48dea8d9744/src/Components/ScheduleList). Not sure how we want to handle this situation. 🤔

@nunomaduro (and @billysmithers as you opened the original PR with this component), what are your thoughts on this? It looks like the package has more functionality than the one included in core.

### CODE REVIEW

**Comment by billysmithers** [comment]
@owenvoke Thanks for considering me in the discussion. I have no issue in moving to the Laravel core command, as it is then something maintained at that level. However am happy to see what other people think especially if it means losing functionality that users of the Zero framework rely on.

**Comment by nunomaduro** [comment]
The "schedule-list" component is an opt-in? If yes, maybe we leave it?

**Comment by billysmithers** [comment]
@nunomaduro As far as I know it is an opt-in. @owenvoke would there be conflicts with the core command if we left the component in place, I think they share the same signature?

**Comment by nunomaduro** [comment]
I think the component will override the existing one. So it's fine.

**Comment by owenvoke** [comment]
Ah, if it overrides the one from core, then that's fine. I'll have a quick test to double check and then release this. 👌🏻 Cheers both of you for your input!

**Comment by owenvoke** [comment]
Ah, just remembered it doesn't matter as the command isn't registered in Laravel Zero's framework. 👍🏻 Merging.

**Pull request merged**
